### ISSUE TITLE
NestJS 

### ISSUE THREAD

**Issue by Noido** [deepkit/deepkit-framework#204]
Hi how can i use it with NestJs ? 

Thanks

**Comment by timvandam** [comment]
What deepkit feature are you trying to use? You could use the whole deepkit framework as a replacement to nest. You could also use individual deepkit libraries if you prefer that.

You could for instance create a nest pipe and interceptor to do (de)serialization with @deepkit/type

**Comment by Noido** [comment]
I want use deepkit orm in place of prisma

**Comment by marcus-sa** [comment]
@Noido you can easily use the Deepkit ORM if you want.
You'd have to try it out as a part of trial and error though because the lack of documentation, but it is worth it.
https://deepkit.io/library/orm

**Comment by marcus-sa** [comment]
> @marcus-sa Yes but it s the problem 0 docs , 0 sample, 0 tutorial it's too complicated for start a project like that

That's how it is with new open source projects like this. I've been able to put apps into production based on the simple examples shown on the documentation website. Obviously, I had to dig into the source code to be able to understand the logic in depth.
There's a lot that isn't documented, but that's why we as an open community need to share our experiences, knowledge and improve the developer experience.
@marcj has done a crazy job providing us with this, and I know from my own experience that documentation can be a pain in the ass.
