### ISSUE TITLE
AMAZING WORK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by TheNightmareX** [deepkit/deepkit-framework#205]
It is not a issue, I just discovered this repo and just can't help to calm down!!!
THIS IS DEFINITLY A SUPER AWESOME AMAZING WORK!!!!!
It implemented what I always always want to do!!! This is the framework I dreamed all days!!!!!!!
GREATE WORK!!!!!!!!!
THANK YOU!!!!!!!!!!!

**Comment by marcj** [comment]
Thank you, glad you like it!

**Comment by xiangnanscu** [comment]
haha . zhihu visitor here. good kids

**Comment by marcj** [comment]
sweet, but what is zhihu?😅

**Comment by marcj** [comment]
Oh awesome, thank you! Do you have a link for me?

**Comment by marcj** [comment]
> I always want to develop a well-designed Node.js Web Framework, just like Django in Node.js with Dependency Injection, or Angular in backend. The Node.js ecosystem is in dire need of a true large-scale framework.
> 
> But DeepKit not only implemented what I always wanted to implement, but also implemented other awesome features I dreamed, just like the runtime type system!!! I'm really excited!!!

I absolutely agree! I come from PHP with Symfony/Laravel and Java Spring, and always wanted something like that for TypeScript💪 I hope Deepkit is someday what Spring is in Java, or Symfony, or Django. Due to TypeScript's rich type system I think it has potential to be even better than we have seen yet in other languages.

**Comment by marcj** [comment]
You are too kind, thank you🙏
