### ISSUE TITLE
bundlephobia shows 299.9 kB minified and 88.2 kB minified + gzipped for @deepkit/rpc

### ISSUE THREAD

**Issue by 205g0** [deepkit/deepkit-framework#331]
I assume that not all of this is imported to a client or is it? Could you provide numbers by how much a client will increase in bundle size when integrating your rpc lib and its peer dep the runtime types lib?

**Comment by marcj** [comment]
We have no numbers. It depends on what you use and how you build it.

**Comment by 205g0** [comment]
> It depends on what you use 

ok, then what's is typical growth in bundle size if I add your rpc client and its req peer deps?

it's pretty easy to answer with other RPC libs

> and how you build it.

i mean a typical production build or wdym?

and why did you close this issue? if the bundle size is too big, this could be a dealbreaker for users

**Comment by marcj** [comment]
You have to test it with your build tools yourself.

**Comment by 205g0** [comment]
assuming they can tree-shake shouldn't they produce approx. the same size?

and did you never checked the bundle size growth yourself?

**Comment by marcj** [comment]
No, because I don't care about these extra kB. If you care about it you should pick a library that is designed to have a low footprint (and with it less features).
Again, do the tests yourself. If the result is that in your use-case it's too big, then that's okay. Still nothing for me to fix as its not our goal to have minimum bundle size.

**Comment by 205g0** [comment]
>  don't care about these extra kB. 

if it would be just some extra kB haha.

The current front runner trpc comes at 4,5kB on the server, 4,8kB on the client totaling 9,3kB compared to your whopping 88,2kB + the required runtimes type lib.

> If you care about [...] a low footprint

who doesn't? everyone does care about fast loading client

> Again, do the tests yourself.

I don't have the time, and I don't need to: i can't imagine that after tree-shaking it would get close anywhere to 10kB

> its not our goal to have minimum bundle size.

nobody asked you to have a minimum size but some sane initial size would be a good start

thanks for convo, your answers were already very helpful

**Comment by marcj** [comment]
Comparing TRPC with Deepkit is comparing apples with oranges. TRPC is a very thin abstraction layer that has a **lot** less features and needs at least superjson and zod to come even close (which increases bundle size), hence why it is itself so small. Maybe you should compare it correctly before jumping to conclusions. 

If you don't utilise runtime type and the features of Deepkit, there's no point of using it. If TRPC is all you need, you should use it. It's a good library. I'm not here to convince you otherwise. If you want to trash talk about bundle size and compare completely wrong feature-sets, feel free to do so, but I'm not discussing that as it's entirely pointless. Let me know if you have glued something together with TRPC/superjson/zod that supports the stuff Deepkit supports like nominal classes, TypeScript type serialisation/validation, binary protocols, and its performance, then I'd love to see the bundle size increase you ended up with.

**Comment by 205g0** [comment]
calm down

> trash talk

where did I? this is just your perception. for some devs bundle size is super crucial among other things (such a a lib's ecosystem, adoption, contributor count, etc.) and i just started my due diligence with the really  huge bundle size just for rpc

> TRPC is a very thin abstraction layer that has a lot less features and needs at least superjson and zod 

not entirely true. zod does what your runtime types lib does which I haven't included in my prior comparison. superjson is just 3,9kB more, zod is 10 but perfectly tree-shakeable

zod and your runtime lib are indeed total different beasts and shouldn't be compare. i recognize the brilliance of your runtime types lib but i have to start somewhere and rpc seems to be good and zod is good enough at the end of the day. and as a sidenote, an integration into the tsc (as smart as it is) sounds also a bit risky (what if it gets unmaintained at some point)

> that supports the stuff Deepkit supports like nominal classes, TypeScript type serialisation/validation, binary protocols, and its performance, 

look, i could now go into every of your point but i'd need to go deeper into your framwork. we could debate about benchmarks (there are none) and whatever. you don't have time, I even less and most important, i don't have any motivation

do you really expect people use your lib as a foundation and go all in? you tackling too many things at the same time and freak now out because some random dude questioned the bundle size 

still wish you good luck and all the best 🙂

**Comment by marcj** [comment]
Nobody is freaking out, please calm down with your personal attacks. 

The point still holds: You compare apple to oranges and wonder why the bundle size is so different. Again, it's because they do very different things. Why else would there be such a big difference? We do not have dead code laying around that nobody uses. If TRPC, superjson, and zod is good enough for you, then you should really use it. They are great.

> sounds also a bit risky

Every time you use an open source library it's risky since it can happen for every project that it gets unmaintained at some point. Nothing special here about Deepkit.

> do you really expect people use your lib as a foundation and go all in?

Dude, calm down. I don't care if you use it or not, or if you think I tacke too many things at the same time.

With that being said, I don't think there is anything else to add to this thread.

**Comment by 205g0** [comment]
> Nobody is freaking out, please calm down with your personal attacks.

you started. and again where are personal attacks? if so i am sorry

> You compare apple to oranges 

no i don't but at this point, let's agree to disagree

> Why else would there be such a big difference? 

you tell me.

> Every time you use an open source library it's risky

not true, some are more mature and have more maintainers, yours will also get there but pretending it's now risk...?

>  don't think there is anything else to add to this thread.

i agree

**Comment by mlynchdev** [comment]
> Comparing TRPC with Deepkit is comparing apples with oranges. TRPC is a very thin abstraction layer that has a **lot** less features and needs at least superjson and zod to come even close (which increases bundle size), hence why it is itself so small. Maybe you should compare it correctly before jumping to conclusions.
> 
> If you don't utilise runtime type and the features of Deepkit, there's no point of using it. If TRPC is all you need, you should use it. It's a good library. I'm not here to convince you otherwise. If you want to trash talk about bundle size and compare completely wrong feature-sets, feel free to do so, but I'm not discussing that as it's entirely pointless. Let me know if you have glued something together with TRPC/superjson/zod that supports the stuff Deepkit supports like nominal classes, TypeScript type serialisation/validation, binary protocols, and its performance, then I'd love to see the bundle size increase you ended up with. I bet it's even bigger than Deepkit, not to speak about its slow performance.

How many times are you going back and forth between not caring about bundle size (for your project) but that the overhead of Zod and SuperJSON matter for tRPC?  This is starting to get as petty as the usual “Redux is dead” conversations.
