### ISSUE TITLE
Using decorated classes inside another module

### ISSUE THREAD

**Issue by ukarlsson** [deepkit/deepkit-framework#52]
Hello, thanks for your investment in marshal.ts, we really appreciate it.

I was running into an issue when I have a multi-module project.

We have basically packages

* server
* client
* domain

In domain we have shared classes using marshal decoration, and then we serialize and deserialize in client and server. Now it seems like the decorations are not picked up if we try to use marshal from client or server, only when we call marshal from the domain package.

I had to set up wrappers like these in the domain package in order to make it work

```
export function validatedPlainToClass<T>(classType: ClassType<T>, data: object, parents?: any[]): T {
  return marshal.validatedPlainToClass(classType, data, parents)
}

export function classToPlain<T>(
  classType: ClassType<T>,
  target: T,
  options?: {
    excludeReferences?: boolean
  }
): any {
  return marshal.classToPlain(classType, target, options)
}
```

It seems to be the same issue as they have in class-transformer

https://github.com/typestack/class-transformer/issues/337

I was thinking maybe you knew why this is an issue, it seems very strange to me!

**Comment by marcj** [comment]
That's an issue with nominal types and Node's module resolution algorithm with mono-repos in general. Essential it means that node resolves the "wrong" Marshal instance and thus stores decorators to the wrong scope. I assume you have in all packages Marshal as dependency, which means you have basically 3 Marshal scopes installed. If you now import a model from `core` in your package `server`, the decorators data are stored in `core/marshal`, while you access `server/marshal` to serialize. This results in undecorated models in your server/client package. You will have the same issue when working with RxJS for example and creating a `Observable` in `core` while consuming them in `server` or whatever. They are not the same nominal type and a check like `instanceof Observable` will fail. 

You have several ways around that when working with symlinked packages. 

1. Put Marshal in the `core` package as `peerDependency` and `devDependency` and make sure `devDependency` are not installed in `core`. This way when the `server` (or client) imports a model from `core`, Node's module resolution picks the Marshal instance from `server` to decorate stuff. This is not the best solution since it breaks your development workflow since devDependencies are not installed, and thus uni tests, type checking etc will break.
2. Put Marshal in the `core` package as `peerDependency` and `devDependency`, and use a program like [npm-local-development](https://github.com/marcj/npm-local-development). This links `core` correctly into your `server`/`client` packages so that devDependencies are excluded. 

Read the README from npm-local-development to understand the issue with nominal types and mono-repos/linked packages better.

These solutions work only if you activate `preserveSymlinks` option when executing node **or** when you hoist your packages all in your root node_modules. If you don't have hoist you need to enabled preserve symlinks using `NODE_PRESERVE_SYMLINKS=1 node myscript.js`, or `node --preserve-symlinks myscript.js`, or in Angular with `"preserveSymlinks": true,` in `angular.json`. For hoist you need to make sure that all 3 packages use a compatible range of Marshal versions so they can be [deduped](https://docs.npmjs.com/cli/dedupe).

I use for all my isomorphic Typescript projects the 2. way. With super hornet we will also provide an example project structure with classical client, server, core structure with everything in place already.

**Comment by marcj** [comment]
That being said, I recently changed the way how Marshal stores its decorator data in a way that it tries to find a global object first before falling back to the local package scope. See https://github.com/super-hornet/super-hornet.ts/commit/c86b7d6cdbf909443297efcde9076ef114cd4916#diff-799b058c6e7172688b9ef93ee5037a40. This will also fix this issue, however you face still other nominal type issues in mono-repos as explained in npm-local-development.

**Comment by ukarlsson** [comment]
Many thanks for the extensive answer and the pointers to the fix. I will try to use the latest version as suggested. Really appreciate it! :+1:

**Comment by marcj** [comment]
Btw, https://nx.dev/ basically fixes this as well, as all node_modules are stored deduped in the root folder. Most projects don't need Lerna (which has node_modules in root only when hoist is enabled). For normal closed-source projects I'd recommend nx.dev.
