### ISSUE TITLE
validation of literal types not working

### ISSUE THREAD

**Issue by i-am-ian** [deepkit/deepkit-framework#578]
I came across the following issue using `deepkit/type 1.0.1-alpha.151`:

```
type MyType = 'StringLiteral';
class MyClass {
    myProperty!: MyType
}
const myObject = {
    myProperty: 'NotMyType'
};
const value = cast<MyClass>(myObject);
```

I would expect `cast` to throw a `ValidationError` because `'NotMyType'` is not compatible with the type `MyType`. Instead, no error is thrown and `value.myProperty` has the value `StringLiteral`. Using options of `{ loosely: false }` does not change the behavior.

**Comment by marcj** [comment]
mh, interesting one. a type/property that has a string literal defined strictly speaking doesn't event care what you pass, it simply sets it to the string literal (since there is no need to do any conversion, it is a static string). `value` thus has the correct shape as described in MyClass, so the cast was successful.

**Comment by marcj** [comment]
closing as working as expected
